### ISSUE TITLE
Cannot find module '@textile/threads-client-grpc/api_pb_service'

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-threads#219]
I've seen this a few times when trying to run the compiled version of a node app (maybe more than node).

```
> node dist/index

internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@textile/threads-client-grpc/api_pb_service'
Require stack:
- /Users/andrewhill/Textile/opensource/ts-express/node_modules/@textile/threads-client/dist/index.js
- /Users/andrewhill/Textile/opensource/ts-express/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/andrewhill/Textile/opensource/ts-express/node_modules/@textile/threads-client/dist/index.js:41:26)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/andrewhill/Textile/opensource/ts-express/node_modules/@textile/threads-client/dist/index.js',
    '/Users/andrewhill/Textile/opensource/ts-express/dist/index.js'
  ]
}
```

My tsconfig is just the default

```
{
  "compilerOptions": {
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */
    "strict": true,                           /* Enable all strict type-checking options. */
    "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    "skipLibCheck": true,                     /* Skip type checking of declaration files. */
    "forceConsistentCasingInFileNames": true  /* Disallow inconsistently-cased references to the same file. */
  }
}
```

**Comment by carsonfarmer** [comment]
Fixed in master and just released, see @textile/threads-client@0.4.0. This was due to a downstream change (go-threads) in how the protobuf types were named.

**Comment by carsonfarmer** [comment]
Closing this as it should be fixed, please reopen if updating still causes issues.

**Comment by andrewxhill** [comment]
Hmm... I seem to be getting this again,

```
Error: Unable to resolve module `@textile/threads-client-grpc/api_pb_service` from `node_modules/@textile/textile/node_modules/@textile/threads-client/dist/index.js`: @textile/threads-client-grpc/api_pb_service could not be found within the project.
```

Here are my installs

```
├── @textile/context@0.3.0
├── @textile/textile@0.2.1
├── @textile/threads-client@0.4.2
├── @textile/threads-core@0.1.11
├── @textile/threads-id@0.0.9
```

This is from trying to update the react-native-hub example to latest APIs

**Comment by carsonfarmer** [comment]
Is this still happening @andrewxhill?

**Comment by andrewxhill** [comment]
not sure the exact source of the error. i was getting this during react native development. basic removal of modules etc didn't fix it. i ended up blasting global npm cache, simulator memory, everything, and it then worked again.
