### ISSUE TITLE
Response closed without headers on `Client.newCollection()`

### ISSUE THREAD

**Issue by ShishKabab** [textileio/js-threads#329]
**Describe the bug**
Using the `Client` from `@textile/hub`, when I call `newCollection()`, I get this error:
```
Error: Response closed without headers
    at Object.onEnd (/home/vincent/Documents/Develop/Web/WorldBrain/storex-workspace/apps/storex-hub-ipfs-textile/node_modules/@textile/hub/node_modules/@textile/threads-client/src/index.ts:672:20)
    at /home/vincent/Documents/Develop/Web/WorldBrain/storex-workspace/apps/storex-hub-ipfs-textile/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:24910
    at Array.<anonymous> (/home/vincent/Documents/Develop/Web/WorldBrain/storex-workspace/apps/storex-hub-ipfs-textile/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:5649)
    at e (/home/vincent/Documents/Develop/Web/WorldBrain/storex-workspace/apps/storex-hub-ipfs-textile/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:1531)
    at Timeout._onTimeout (/home/vincent/Documents/Develop/Web/WorldBrain/storex-workspace/apps/storex-hub-ipfs-textile/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:1645)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

```

Notice the stack trace didn't give me any useful information on where this error occurred in my program, had to figure that out myself. Would be a good thing to improve.

**To Reproduce**
It's a bit hard to replicate my setup, but the code is here:
https://github.com/WorldBrain/storex-hub-ipfs-textile/blob/02ba1fc3f0094f16da32c63ed7377b5c20ce6db8/ts/application.ts#L94

**Expected behavior**
Since I probably did something wrong (I'm not clear from the docs how identity and tokens work for example), I expect a useful error message. Did I pass in wrong params to the `newCollection()` method? Does it need more authentication? Could it not connect to Textile Hub? Is this even the right code to connect to Textile Hub?

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS
 - Browser: Node.js
 - Version 12.16.3

**Comment by carsonfarmer** [comment]
Agreed, that's not a very good error message. Its the message that comes from the underlying gRPC client when there wasn't a valid response from the service. But we should defs be able to catch this one and provide more context. We'll use this ticket for tracking that.

**Comment by carsonfarmer** [comment]
I noticed from your code that getToken or getTokenChallenge are commented out/not used. This is likely the cause of the error? Before performing any operations on the remote Hub host, you'll need to complete the identity challenge that is `getToken` (or getTokenChallenge if you'd prefer a callback to do your key signing). We've just updated the docs, so this might be a good example to see how that auth flow works: https://github.com/textileio/js-examples/blob/master/hub-browser-auth-app/src/client/index.ts

**Comment by ShishKabab** [comment]
I don't want to overload this thread, but I've just tried doing `getToken()` and still the same result. This is blocking me progressing. I skimmed over the notice that `getToken()` actually modifies the client. Maybe it's useful to rename this method so it's clearer that this modifies things, like `authenticate()`? I've just checked the docs and it's not clear to me what token with the token from the docs. (Did a search for `token` in the page, but it's only mentioned at `getToken()`, but not used anywhere.)

Do you prefer we continue this conversation on Slack, so leave this thread clean, and I open issues for different documentation issues as they arise from the conversation?

**Comment by carsonfarmer** [comment]
Yes good call, let’s move the conversation to slack. Feel free to introduce yourself there to myself @carsonfarmer and @andrewxhill (same usernames in slack). As you suggest, we can created separate issues as they arise to keep them ‘clean’ for future readers.

**Comment by carsonfarmer** [comment]
The issue has been tracked down to a panic upon adding an empty json-schema. The panic has been caught, and it should now return a much more useful error message. See https://github.com/textileio/go-threads/pull/387
